#Returns the ratio of the yields for a given sample and place into Ratios.txt
#Input is the desired min pt value to compare the pregenerated min pt folders using the TruthAnalysis.sh script.
#Run in the respective folder that contains the folders that are run over.
#!/bin/bash
if [ $2 == "DYmumu" ]; then
    root -l -q '/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/C_programs/get_TruthAnalysis_Ratio.C("/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/'$3'/ExclWW/excl_'$1'_min_pt/hist-mc16_13TeV.363761.Herwig7EvtGen_BudnevQED_WWlvlv_LeptonFilter.private.DAOD_TRUTH0.e7184_e5984.root", "/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/'$3'/DY/DYmumu_'$1'_min_pt/hist-user.spagan.mc16_13TeV.363282.DYmumu_110M_CTFilter11.private.DAOD_TRUTH0.e7744_e5984.v1_EXT0.root",'$1',"DYmumu")'
elif [ $2 == "Ztautau" ]; then
    root -l -q '/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/C_programs/get_TruthAnalysis_Ratio.C("/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/'$3'/ExclWW/excl_'$1'_min_pt/hist-mc16_13TeV.363761.Herwig7EvtGen_BudnevQED_WWlvlv_LeptonFilter.private.DAOD_TRUTH0.e7184_e5984.root", "/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/'$3'/Ztautau/Ztautau_'$1'_min_pt/hist-user.spagan.mc16_13TeV.3632812.Ztautau_TauFl25l18_CTF11.private.DAOD_TRUTH0.e7744_e5984.v1_EXT0.root",'$1',"Ztautau")'
elif [ $2 == "InclWW" ]; then
    root -l -q '/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/C_programs/get_TruthAnalysis_Ratio.C("/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/'$3'/ExclWW/excl_'$1'_min_pt/hist-mc16_13TeV.363761.Herwig7EvtGen_BudnevQED_WWlvlv_LeptonFilter.private.DAOD_TRUTH0.e7184_e5984.root", "/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/'$3'/InclWW/incl_'$1'_min_pt.root",'$1',"InclWW")'
elif [ $2 == "Zmumu" ]; then
    root -l -q '/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/C_programs/get_TruthAnalysis_Ratio.C("/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/'$3'/ExclWW/excl_'$1'_min_pt/hist-mc16_13TeV.363761.Herwig7EvtGen_BudnevQED_WWlvlv_LeptonFilter.private.DAOD_TRUTH0.e7184_e5984.root", "/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/'$3'/Zmumu/Zmumu_'$1'_min_pt/hist-user.spagan.mc16_13TeV.363280.Zmumu_60M110_CTFilter11.private.DAOD_TRUTH0.e7744_e5984.v1_EXT0.root",'$1',"Zmumu")'
elif [ $2 == "LowMassDY" ]; then
    root -l -q '/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/source/LowPtAnalysis/macros/get_TruthAnalysis_Ratio.C("/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/mumu_analysis/ExclWW/excl_'$1'_min_pt/hist-mc16_13TeV.363761.Herwig7EvtGen_BudnevQED_WWlvlv_LeptonFilter.private.DAOD_TRUTH0.e7184_e5984.root", "/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/mumu_analysis/LowMassDY/Nom/LowMassDY_'$1'_min_pt/hist-Truth0.root",'$1',"LowMassDY")'
fi
