#!/bin/bash
if [ $2 == "DYmumu" ]; then
    root -l '/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/source/LowPtAnalysis/macros/plot_TruthAnalysis-SBStudy.C("/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/'$3'/ExclWW/excl_'$1'_min_pt/hist-mc16_13TeV.363761.Herwig7EvtGen_BudnevQED_WWlvlv_LeptonFilter.private.DAOD_TRUTH0.e7184_e5984.root", "/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/'$3'/DY/DYmumu_'$1'_min_pt/hist-user.spagan.mc16_13TeV.363282.DYmumu_110M_CTFilter11.private.DAOD_TRUTH0.e7744_e5984.v1_EXT0.root","DYmumu")'
elif [ $2 == "Ztautau" ]; then
    root -l '/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/source/LowPtAnalysis/macros/plot_TruthAnalysis-SBStudy.C("/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/'$3'/ExclWW/excl_'$1'_min_pt/hist-mc16_13TeV.363761.Herwig7EvtGen_BudnevQED_WWlvlv_LeptonFilter.private.DAOD_TRUTH0.e7184_e5984.root", "/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/'$3'/Ztautau/Ztautau_'$1'_min_pt/hist-user.spagan.mc16_13TeV.3632812.Ztautau_TauFl25l18_CTF11.private.DAOD_TRUTH0.e7744_e5984.v1_EXT0.root","Ztautau")'
elif [ $2 == "InclWW" ]; then
    root -l '/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/source/LowPtAnalysis/macros/plot_TruthAnalysis-SBStudy.C("/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/'$3'/ExclWW/excl_'$1'_min_pt/hist-mc16_13TeV.363761.Herwig7EvtGen_BudnevQED_WWlvlv_LeptonFilter.private.DAOD_TRUTH0.e7184_e5984.root", "/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/'$3'/InclWW/incl_'$1'_min_pt.root","inclWW")'
elif [ $2 == "Zmumu" ]; then
    root -l '/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/source/LowPtAnalysis/macros/plot_TruthAnalysis-SBStudy.C("/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/'$3'/ExclWW/excl_'$1'_min_pt/hist-mc16_13TeV.363761.Herwig7EvtGen_BudnevQED_WWlvlv_LeptonFilter.private.DAOD_TRUTH0.e7184_e5984.root", "/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/'$3'/Zmumu/Zmumu_'$1'_min_pt/hist-user.spagan.mc16_13TeV.363280.Zmumu_60M110_CTFilter11.private.DAOD_TRUTH0.e7744_e5984.v1_EXT0.root","Zmumu")'
elif [ $2 == "DYee" ]; then
    root -l '/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/source/LowPtAnalysis/macros/plot_TruthAnalysis-SBStudy.C("/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/Excl_Samples/excl_'$1'_min_pt/hist-mc16_13TeV.363761.Herwig7EvtGen_BudnevQED_WWlvlv_LeptonFilter.private.DAOD_TRUTH0.e7184_e5984.root", "/global/projecta/projectdirs/atlas/rgarbutt/AnalysisCode/analysis/run/DY/Excl-DYee-1/DYee_'$1'_min_pt/hist-","DYee")'
fi
